version: '3'
services:
  ispindel:
    build: .
    image: ispindle-tcp-server-docker/ispindle-tcp-server-raspbian
    container_name: ispindle-tcp-server-${ISPINDLE_ID} 
    hostname: ispindle-tcp-server-${ISPINDLE_ID}.local
    ports:
        - 80${ISPINDLE_ID}:80 
    environment:
        - ISPINDLE_ID=${ISPINDLE_ID}
    volumes:
        - ${DATA_DIR}/ispindle-tcp-server-${ISPINDLE_ID}:/data
        # get timezone from host by mounting host settings 
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
    restart: always

networks:
    default:
      driver: bridge
