version: '1'
services:
  db:
    image: percona:5.7
    container_name: ispindle-tcp-server-${ISPINDLE_ID}
    environment:
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASSWORD}
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  ispindel:
    build: .
    image: ispindle-tcp-server-docker/ispindle-tcp-server-raspbian
    container_name: ispindle-tcp-server-${ISPINDLE_ID} 
    hostname: ispindle-tcp-server-${ISPINDLE_ID}.local
    ports:
        - 80${ISPINDLE_ID}:80 
    environment:
        - ISPINDLE_ID=${ISPINDLE_ID}
    volumes:
        - ${DATA_DIR}/ispindle-tcp-server-${ISPINDLE_ID}:/data
        # get timezone from host by mounting host settings 
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
    restart: always

networks:
    default:
      driver: bridge
